name: publish nodejs package
description: publish nodejs package
inputs:
    on_finished:
        description: Run a bash on finished.
        required: false
    on_publish_failed:
        description: Run a bash on publish failed.
        required: false
outputs:
    failed:
        description: "Random number"
        value: ${{ steps.nodejs.outputs.id == '' || steps.output_failure.outputs.failed == 'true' }}

runs:
    using: 'composite'
    steps:
        name: Remove NodeJS Release
        if: always()
        shell: bash
        run: |
            eval $ON_FINISHED || echo "::warning::Failed to eval $ON_FINISHED"
        env:
            ON_FINISHED: ${{ inputs.on_finished }}
      -
        name: Output Failure
        id: output_failure
        if: failure() || steps.nodejs.outputs.id == ''
        shell: bash
        run: |
            eval $ON_PUBLISH_FAILED || echo "::warning::Failed to eval $ON_PUBLISH_FAILED"
            echo "failed=true" >> $GITHUB_OUTPUT
        env:
            ON_PUBLISH_FAILED: ${{ inputs.on_publish_failed }}
